default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: localhost

development:
  <<: *default
  database: todos_development

test:
  <<: *default
  database: todos_test

production:
  url: <%= ENV['DATABASE_URL'] %>
